blank_issues_enabled: true
contact_links:
  - name: Just ask the community a question
    url: https://github.com/deepsh/deepsh/discussions/categories/q-a
    about: Community help about usage the deepsh shell.
